language: c


script:
  - cd seccomp
  - sudo dpkg -i libseccomp2_2.5.1-1ubuntu1~20.04.1_amd64.deb
  - sudo dpkg -i libseccomp-dev_2.5.1-1ubuntu1~20.04.1_amd64.deb
  - sudo dpkg -i seccomp_2.5.1-1ubuntu1~20.04.1_amd64.deb
  - cd ../build
  - make